-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 16:09:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema P6_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `P6_db`;

-- -----------------------------------------------------
-- Schema P6_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P6_db` DEFAULT CHARACTER SET utf8;
USE `P6_db`;

-- -----------------------------------------------------
-- Table `P6_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`user`;

CREATE TABLE IF NOT EXISTS `P6_db`.`user`
(
    `id`         INT           NOT NULL AUTO_INCREMENT,
    `lastname`   VARCHAR(50)   NOT NULL,
    `firstname`  VARCHAR(50)   NOT NULL,
    `email`      VARCHAR(50)   NOT NULL,
    `password`   VARCHAR(255)  NOT NULL,
    `balance`    DECIMAL(9, 2) NOT NULL DEFAULT 0,
    `createDate` DATETIME      NOT NULL DEFAULT now(),
    `isActive`   TINYINT       NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P6_db`.`bank_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`bank_account`;

CREATE TABLE IF NOT EXISTS `P6_db`.`bank_account`
(
    `iban`        VARCHAR(34)  NOT NULL,
    `bic`         VARCHAR(50)  NOT NULL,
    `bankName`    VARCHAR(255) NOT NULL,
    `accountName` VARCHAR(255) NOT NULL,
    `user_id`     INT          NOT NULL,
    PRIMARY KEY (`iban`),
    INDEX `fk_bank_account_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_bank_account_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `P6_db`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P6_db`.`tranfert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`tranfert`;

CREATE TABLE IF NOT EXISTS `P6_db`.`tranfert`
(
    `id`              INT           NOT NULL AUTO_INCREMENT,
    `amount`          DECIMAL(9, 2) NOT NULL,
    `description`     VARCHAR(255)  NULL,
    `transactionDate` DATETIME      NOT NULL DEFAULT now(),
    `status`          VARCHAR(50)   NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P6_db`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`relation`;

CREATE TABLE IF NOT EXISTS `P6_db`.`relation`
(
    `owner_id` INT NOT NULL,
    `buddy_id` INT NOT NULL,
    PRIMARY KEY (`owner_id`, `buddy_id`),
    INDEX `fk_relation_user2_idx` (`buddy_id` ASC) VISIBLE,
    CONSTRAINT `fk_relation_user1`
        FOREIGN KEY (`owner_id`)
            REFERENCES `P6_db`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_relation_user2`
        FOREIGN KEY (`buddy_id`)
            REFERENCES `P6_db`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P6_db`.`transfert_statut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`transfert_statut`;

CREATE TABLE IF NOT EXISTS `P6_db`.`transfert_statut`
(
    `id`    INT         NOT NULL AUTO_INCREMENT,
    `label` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `label_UNIQUE` (`label` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P6_db`.`internal_transfert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`internal_transfert`;

CREATE TABLE IF NOT EXISTS `P6_db`.`internal_transfert`
(
    `tranfert_id` INT NOT NULL,
    `user_id`     INT NOT NULL,
    `user_id1`    INT NOT NULL,
    PRIMARY KEY (`tranfert_id`),
    INDEX `fk_internal_transfert_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_internal_transfert_user2_idx` (`user_id1` ASC) VISIBLE,
    CONSTRAINT `fk_internal_transfert_tranfert1`
        FOREIGN KEY (`tranfert_id`)
            REFERENCES `P6_db`.`tranfert` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_internal_transfert_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `P6_db`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_internal_transfert_user2`
        FOREIGN KEY (`user_id1`)
            REFERENCES `P6_db`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P6_db`.`external_transfert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P6_db`.`external_transfert`;

CREATE TABLE IF NOT EXISTS `P6_db`.`external_transfert`
(
    `tranfert_id`       INT           NOT NULL,
    `bank_account_iban` VARCHAR(34)   NOT NULL,
    `fees`              DECIMAL(9, 2) NOT NULL DEFAULT 0,
    PRIMARY KEY (`tranfert_id`),
    INDEX `fk_external_transfert_bank_account1_idx` (`bank_account_iban` ASC) VISIBLE,
    CONSTRAINT `fk_external_transfert_tranfert1`
        FOREIGN KEY (`tranfert_id`)
            REFERENCES `P6_db`.`tranfert` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_external_transfert_bank_account1`
        FOREIGN KEY (`bank_account_iban`)
            REFERENCES `P6_db`.`bank_account` (`iban`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
